import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar da Central de Ajuda (autogerada a partir da estrutura de pastas em docs/).
// A ordem das categorias/itens vem dos _category_.json e do sidebar_position do frontmatter.
const sidebars: SidebarsConfig = {
  helpSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
