import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar da Documentação de API (autogerada a partir de api/).
// Categorias definidas via _category_.json em api/.
const sidebars: SidebarsConfig = {
  apiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
