// Generated by scripts/generate-conversation-types.mjs. Do not edit.

export type ActionId = "importar-contatos" | "abrir-robos" | "abrir-usuarios" | "abrir-canais" | "abrir-campanhas" | "abrir-departamentos" | "abrir-atendimento" | "abrir-crm";

export type GuideId = "importar-contatos" | "robo-de-atendimento" | "usuario-acesso" | "reconectar-canal-qr" | "campanhas" | "permissoes-departamentos" | "arquivos" | "crm";

export type GuideV1 = {
  schemaVersion: 1;
  guideId: "importar-contatos" | "robo-de-atendimento" | "usuario-acesso" | "reconectar-canal-qr" | "campanhas" | "permissoes-departamentos" | "arquivos" | "crm";
  version: number;
  mode: "real" | "treino";
  initialStepId: string;
  steps: Array<{
  stepId: string;
  text: string;
  actionId?: "importar-contatos" | "abrir-robos" | "abrir-usuarios" | "abrir-canais" | "abrir-campanhas" | "abrir-departamentos" | "abrir-atendimento" | "abrir-crm";
  choices?: Array<{
  id: string;
  label: string;
  nextStepId?: string;
}>;
}>;
};

export type AssistantRequestV1 = {
  schemaVersion: 1;
  question: string;
  guide?: {
  guideId: "importar-contatos" | "robo-de-atendimento" | "usuario-acesso" | "reconectar-canal-qr" | "campanhas" | "permissoes-departamentos" | "arquivos" | "crm";
  stepId: string;
  version: number;
  mode: "real" | "treino";
  pendingChoiceId?: string;
  choiceId?: string;
};
};

export type AssistantReplyV1 = {
  schemaVersion: 1;
  answer: string;
  guide?: {
  guideId: "importar-contatos" | "robo-de-atendimento" | "usuario-acesso" | "reconectar-canal-qr" | "campanhas" | "permissoes-departamentos" | "arquivos" | "crm";
  stepId: string;
  version: number;
  mode: "real" | "treino";
  pendingChoiceId?: string;
  choiceId?: string;
};
  actions?: Array<{
  id: "importar-contatos" | "abrir-robos" | "abrir-usuarios" | "abrir-canais" | "abrir-campanhas" | "abrir-departamentos" | "abrir-atendimento" | "abrir-crm";
  label: string;
  route: string;
  target?: string;
}>;
};

export type ProductActionV1 = {
  id: "importar-contatos" | "abrir-robos" | "abrir-usuarios" | "abrir-canais" | "abrir-campanhas" | "abrir-departamentos" | "abrir-atendimento" | "abrir-crm";
  label: string;
  route: string;
  target?: string;
};

