// Generated by scripts/generate-conversation-types.mjs. Do not edit.

export type ActionId = "importar-contatos" | "abrir-robos" | "abrir-usuarios" | "abrir-canais" | "abrir-campanhas" | "abrir-departamentos" | "abrir-atendimento" | "abrir-crm";

export type GuideId = "guia-importar-contatos" | "robo-de-atendimento" | "usuario-acesso" | "reconectar-canal-qr" | "campanhas" | "permissoes-departamentos" | "arquivos" | "crm";

export type GuideV1 = {
  schemaVersion: 1;
  guideId: "guia-importar-contatos" | "robo-de-atendimento" | "usuario-acesso" | "reconectar-canal-qr" | "campanhas" | "permissoes-departamentos" | "arquivos" | "crm";
  version: number;
  mode: "real" | "treino";
  initialStepId: string;
  steps: Array<{
  stepId: string;
  text: string;
  actionId?: "importar-contatos" | "abrir-robos" | "abrir-usuarios" | "abrir-canais" | "abrir-campanhas" | "abrir-departamentos" | "abrir-atendimento" | "abrir-crm";
  choices?: Array<{
  id: string;
  label: string;
  nextStepId?: string;
}>;
}>;
};

export type AssistantRequestV1 = {
  schemaVersion?: 1;
  question: string;
  history?: Array<{
  role: "user" | "assistant";
  content: string;
}>;
  scope?: "Tudo" | "Ajuda e FAQ" | "API" | "Tutoriais" | "Novidades";
  page?: {
  path: string;
  title: string;
};
  widgetContext?: {
  surface?: "faq" | "app";
  route?: "/contact" | "/bot" | "/configuracoes/user" | "/configuracoes/channel" | "/campanhas" | "/configuracoes/department" | "/atendimento" | "/crm/pipeline";
  module?: "robots" | "users" | "channels" | "billing" | "campaigns" | "templates" | "conversations" | "settings";
  screen?: "list" | "create" | "edit" | "detail" | "connection" | "qr" | "unknown";
  role?: "owner" | "admin" | "manager" | "agent" | "unknown";
  permissions?: Array<"robots.read" | "robots.create" | "users.read" | "users.manage" | "channels.read" | "channels.manage" | "billing.read" | "campaigns.read" | "campaigns.create" | "templates.read" | "templates.manage">;
  plan?: "trial" | "active" | "expired" | "limited" | "unknown";
  channels?: Array<{
  kind: "whatsapp" | "official_api" | "coexistence";
  state: "connected" | "disconnected" | "qr_pending" | "blocked" | "syncing" | "unknown";
}>;
  credit?: "available" | "low" | "empty" | "unknown";
  templates?: "none" | "pending" | "approved" | "rejected" | "unknown";
  incidents?: Array<"channel_outage" | "message_delivery" | "billing" | "robot" | "app">;
};
  guide?: {
  guideId: "guia-importar-contatos" | "robo-de-atendimento" | "usuario-acesso" | "reconectar-canal-qr" | "campanhas" | "permissoes-departamentos" | "arquivos" | "crm";
  stepId: string;
  version: number;
  mode: "real" | "treino";
  pendingChoiceId?: string;
  pendingChoice?: string;
  choiceId?: string;
};
};

export type AssistantReplyV1 = {
  schemaVersion?: 1;
  answer: string;
  sections?: Array<{
  title: string;
  items: Array<string>;
}>;
  steps?: Array<{
  text: string;
  action?: {
  id: "importar-contatos" | "abrir-robos" | "abrir-usuarios" | "abrir-canais" | "abrir-campanhas" | "abrir-departamentos" | "abrir-atendimento" | "abrir-crm";
  label?: string;
  route: string;
  target?: string;
};
  image?: {
  src: string;
  alt: string;
};
}>;
  code?: {
  language: string;
  content: string;
} | null;
  sources?: Array<{
  title: string;
  path: string;
  kind?: "Ajuda" | "FAQ" | "API" | "Tutorial" | "Novidade";
  excerpt?: string;
  media?: {
  kind: "video" | "tango";
  url: string;
  embedUrl?: string;
};
}>;
  suggestions?: Array<string>;
  resolution?: "complete" | "partial" | "not_found";
  found?: boolean;
  diagnosis?: {
  cause: "usage" | "configuration" | "permission" | "plan" | "channel_qr" | "meta_coexistence" | "bug_incident" | "sensitive_action";
};
  escalation?: {
  intent: "create_robot" | "manage_users" | "connect_channel" | "billing" | "campaigns" | "templates" | "departments" | "files" | "crm" | "get_help";
  diagnosis: "usage" | "configuration" | "permission" | "plan" | "channel_qr" | "meta_coexistence" | "bug_incident" | "sensitive_action";
  state?: {
  surface?: "faq" | "app";
  route?: "/contact" | "/bot" | "/configuracoes/user" | "/configuracoes/channel" | "/campanhas" | "/configuracoes/department" | "/atendimento" | "/crm/pipeline";
  module?: "robots" | "users" | "channels" | "billing" | "campaigns" | "templates" | "conversations" | "settings";
  screen?: "list" | "create" | "edit" | "detail" | "connection" | "qr" | "unknown";
  role?: "owner" | "admin" | "manager" | "agent" | "unknown";
  permissions?: Array<"robots.read" | "robots.create" | "users.read" | "users.manage" | "channels.read" | "channels.manage" | "billing.read" | "campaigns.read" | "campaigns.create" | "templates.read" | "templates.manage">;
  plan?: "trial" | "active" | "expired" | "limited" | "unknown";
  channels?: Array<{
  kind: "whatsapp" | "official_api" | "coexistence";
  state: "connected" | "disconnected" | "qr_pending" | "blocked" | "syncing" | "unknown";
}>;
  credit?: "available" | "low" | "empty" | "unknown";
  templates?: "none" | "pending" | "approved" | "rejected" | "unknown";
  incidents?: Array<"channel_outage" | "message_delivery" | "billing" | "robot" | "app">;
};
  attempts: Array<"documented_guide" | "reported_stuck">;
};
  guide?: {
  guideId: "guia-importar-contatos" | "robo-de-atendimento" | "usuario-acesso" | "reconectar-canal-qr" | "campanhas" | "permissoes-departamentos" | "arquivos" | "crm";
  stepId: string;
  version: number;
  mode: "real" | "treino";
  pendingChoiceId?: string;
  pendingChoice?: string;
  choiceId?: string;
};
  actions?: Array<{
  id: "importar-contatos" | "abrir-robos" | "abrir-usuarios" | "abrir-canais" | "abrir-campanhas" | "abrir-departamentos" | "abrir-atendimento" | "abrir-crm";
  label?: string;
  route: string;
  target?: string;
}>;
  model?: string;
};

export type ProductActionV1 = {
  id: "importar-contatos" | "abrir-robos" | "abrir-usuarios" | "abrir-canais" | "abrir-campanhas" | "abrir-departamentos" | "abrir-atendimento" | "abrir-crm";
  label?: string;
  route: string;
  target?: string;
};

